version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
      time: '03:00'
      timezone: Europe/Helsinki
    open-pull-requests-limit: 99
    versioning-strategy: lockfile-only
    rebase-strategy: disabled
